### ISSUE TITLE
[Support] Links broken in tables

### ISSUE THREAD

**Issue by vbwright** [DifuseHQ/Kalmia#11]
* **I'm submitting a**:

   - [x] Support Request

* **Do you want to request a feature or report a bug?**
Not until I know whether this is an intended behavior.

* **What is the current behaviour?**
When a table is created, text entered into a cell is visible on save. However, making the text a link (highlighting text > Create link) causes both the text and link not to appear in the cell outside of editing mode.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a table on a Page, enter text into a cell, create a link from it. When saved, the text and link fail to appear.

* **What is the expected behaviour?**
A link should appear in the cell.

| Expected | Experienced |
|--------|--------|
| [Link](https://github.com/DifuseHQ/Kalmia/) |  | 

* **What is the motivation / use case for changing the behavior?**
Putting links in a table :)

* **Please tell us about your environment**

  * **Version**: kalmia_0.0.2_linux_amd64
  * **Browser**: [all]
  * **Operating System** (where kalmia is running): Linux (Debian 12.7.0_amd64)

**Comment by hayzamjs** [comment]
Good catch! I've fixed it in this commit https://github.com/DifuseHQ/Kalmia/commit/f99e5aaaea4c87a174b834febd6edd37036f48bf, please try it out if you can, reopen the issue if there's anything I've missed.
