### ISSUE TITLE
Invalid request data

### ISSUE THREAD

**Issue by madeus** [DifuseHQ/Kalmia#4]
* **Version**: 0.0.1
  * **Database**: SQLite
  * **Nginx**: 1.20.1
  * **Browser**: Chrome 127.0.6533.120
  * **Operating System**: Rocky Linux 9.4
  * **Kalmia home directory**: _/opt/kalmia_

I installed Kalmia according to the [documentation](https://kalmia.difuse.io/doc/guides/getting-started/detailed-setup-guide.html). When adding a new documentation page, I get the error "Invalid request data". It doesn't matter if I do it from the admin account or another. I fill in all the required fields, add them, modify them, change the values. Nothing helps. 

The Kalmia service works correctly, Ngnix works correctly, no errors in the logs. The only error I see is in the Developer Tools:

```
POST https://docs.*****.pl/kal-api/docs/documentation/create 400 (Bad Request)

(anonymous) @ 9651.ae49fc1b.js:1
xhr @ 9651.ae49fc1b.js:1
c @ 2594.d694ffa7.js:1
Promise.then
_request @ 8104.2388b5eb.js:5
request @ 8104.2388b5eb.js:5
(anonymous) @ 8104.2388b5eb.js:5
(anonymous) @ 8104.2388b5eb.js:5
i @ index~4c6f7b61.2b05e2fd.js:1
m @ index~4c6f7b61.2b05e2fd.js:1
ed @ index~8b82dbae.262d9505.js:1
eU @ 9890.8f20f2f6.js:1
eW @ 9890.8f20f2f6.js:1
(anonymous) @ 9890.8f20f2f6.js:1
re @ 9890.8f20f2f6.js:1
rn @ 9890.8f20f2f6.js:1
(anonymous) @ 9890.8f20f2f6.js:1
oN @ 9890.8f20f2f6.js:1
eR @ 9890.8f20f2f6.js:1
ro @ 9890.8f20f2f6.js:1
nU @ 9890.8f20f2f6.js:1
nO @ 9890.8f20f2f6.js:1
index~8b82dbae.262d9505.js:1 false
```

My configuration file looks like this:

```
{
  "environment": "production",
  "port": 2727,
  "database": "sqlite",
  "logLevel": "debug",
  "sessionSecret": "***********************************",
  "users": [
    {
      "username": "admin",
      "email": "admin@*****.pl",
      "password": "*********",
      "admin": true
    },
    {
      "username": "user",
      "email": "user@*****.pl",
      "password": "*********",
      "admin": false
    }
  ]
}
```
I would be grateful for your help.

**Comment by hayzamjs** [comment]
Thank you for the detailed report! The error that you shared usually gets hit when some value or the other is not entered correctly (could also very well be a bug that we missed), the problem is that only the [0.0.2](https://github.com/DifuseHQ/Kalmia/releases/tag/0.0.2) version has the detailed response from the server (as to which field is going haywire). Could you please update to it and check the response from the server? It should ideally look something like this (in your network -> response tab of your browser for that request):

```json
{"status": "error", "message": "invalid_request_data", "error": "<error here>"}
```

The `<error here>` would be helpful to troubleshoot

**Comment by madeus** [comment]
It was really fast. ;-) And after the update it works as it should. Interestingly, I used exactly the same data in the same fields. I will happily test it further. It looks very promising, and thanks for the help.

**Comment by hayzamjs** [comment]
Perfect! We made some improvements there in the v0.0.2 version, perhaps it got fixed there.
